### ISSUE TITLE
Qwen2.5 VL in compatible with torch 2.7 and flash attn 2.8: AttributeError("'constexpr' object has no attribute 'bit_length'")

### ISSUE THREAD

**Issue by hebiao064** [volcengine/verl#2405]
When I bump verl's env to torch 2.7 and flash-attn 2.8, qwen2.5 vl training will fail with below issue:

```bash
triton.compiler.errors.CompilationError: at 32:28:
    # Meta-parameters
    # We want ROTARY_DIM to be constexpr, otherwise the triton compiler doesn't know that
    # the mask is constant every 8 elements, and it will generate LDG.16 instead of LDG.128
    ROTARY_DIM: tl.constexpr,
    IS_SEQLEN_OFFSETS_TENSOR: tl.constexpr,
    IS_VARLEN: tl.constexpr,
    INTERLEAVED: tl.constexpr,
    CONJUGATE: tl.constexpr,
    BLOCK_H: tl.constexpr,
    BLOCK_M: tl.constexpr,
):
    BLOCK_K: tl.constexpr = triton.next_power_of_2(ROTARY_DIM)
                            ^
AttributeError("'constexpr' object has no attribute 'bit_length'")
```

The proposed solution is to pin flash-attn to 2.7.4.post1 but it won't work with torch 2.7

To address this issue, I suggest remove the CI about QWen2.5 VL first (In this PR: https://github.com/volcengine/verl/pull/2187), and once flash-attn/transformer fixed it, we bring it back.

**Comment by vermouth1992** [comment]
What's the root cause of this issue?

**Comment by Kirrito-k423** [comment]
### 中文
定时清理检查结论：这个 issue 最近一次非当前运行账号的公开回复或引用是 `2025-07-15T07:15:13Z`，截至本轮运行时间 `2026-07-10T01:03:01Z` 已经超过 6 个月。检查来源包括 issue comments API `https://api.github.com/repos/verl-project/verl/issues/2405/comments` 和 timeline API `https://api.github.com/repos/verl-project/verl/issues/2405/timeline`；最近证据：https://github.com/verl-project/verl/pull/2398。

因此按社区 issue 定时清理标准关闭。若作者或社区成员仍能提供当前版本的复现、日志、PR 关联或新的需求背景，欢迎继续评论请求重开，或创建一个带有最新证据的新 issue。

### English
Scheduled cleanup check: the latest public reply or reference from an account other than the current automation account was `2025-07-15T07:15:13Z`, which is more than 6 months before this run time `2026-07-10T01:03:01Z`. The checked public sources were the issue comments API `https://api.github.com/repos/verl-project/verl/issues/2405/comments` and the timeline API `https://api.github.com/repos/verl-project/verl/issues/2405/timeline`; latest evidence: https://github.com/verl-project/verl/pull/2398.

Closing this under the scheduled issue cleanup policy. If the author or community can still provide a current reproduction, logs, PR reference, or updated requirement context, please comment to request reopening or open a new issue with fresh evidence.

This response was generated by a scheduled Codex GPT5.5 issue processing task.
