### ISSUE TITLE
When Verl is installed, the vllm error：  '_OpNamespace' '_C' object has no attribute 'rms_norm'

### ISSUE THREAD

**Issue by zyf8818** [volcengine/verl#1084]
![Image](https://github.com/user-attachments/assets/9b7695a8-873c-47f1-ba03-de6bf4c459f4)

![Image](https://github.com/user-attachments/assets/9569bb92-2b96-4fdf-9aaf-bd9f3374aa71)
I have use these installation steps:
conda create -n verl python==3.10
conda activate verl
pip3 install torch==2.6.0 --index-url https://download.pytorch.org/whl/cu126
pip3 install flash-attn --no-build-isolation
git clone https://github.com/volcengine/verl.git
cd verl
pip3 install -e .

**Comment by eric-haibin-lin** [comment]
I think vllm forces a older version of torch

**Comment by zyf8818** [comment]
> I think vllm forces a older version of torch

Which version of torch is suitable for vllm 0.6.3?
I couldnot make the versions of these two packages match

**Comment by 0x404** [comment]
> Which version of torch is suitable for vllm 0.6.3?

I think torch==2.4.0 should work with vllm==0.6.3 (https://github.com/vllm-project/vllm/blob/v0.6.3/requirements-cuda.txt)

**Comment by Kirrito-k423** [comment]
定时清理检查结果：这个 issue 最近一次由当前运行账号以外账号产生的公开回复或公开引用是 `2025-04-15T05:43:29Z`。本轮检查日期为 2026-07-04，该时间已经超过 6 个月。检查来源包括 issue comments API `https://api.github.com/repos/verl-project/verl/issues/1084/comments?per_page=100` 和 timeline API `https://api.github.com/repos/verl-project/verl/issues/1084/timeline?per_page=100`。

按照本仓库的定时 issue 清理标准，我会先留下这条说明并关闭该 issue。若作者或社区成员仍能提供新的复现、证据或需求背景，请继续评论请求重开，或创建新的 issue 并引用这里的上下文。

---

Scheduled cleanup check: the latest public reply or public reference from an account other than the current automation account was `2025-04-15T05:43:29Z`. The check date for this run is 2026-07-04, so that activity is more than 6 months old. The checked public sources were the issue comments API `https://api.github.com/repos/verl-project/verl/issues/1084/comments?per_page=100` and the timeline API `https://api.github.com/repos/verl-project/verl/issues/1084/timeline?per_page=100`.

Following the scheduled issue cleanup policy, I am leaving this note first and then closing the issue. If the author or community can still provide a fresh reproduction, evidence, or requirement context, please comment to request reopening or open a new issue that links back to this one.

This response was generated by a scheduled Codex GPT5.5 issue processing task.
