### ISSUE TITLE
Qwen3-VL models don't have `max_position_embeddings`

### ISSUE THREAD

**Issue by shirley-wu** [volcengine/verl#4807]
### System Info

----------Python Info----------
Version      : 3.12.12
Compiler     : GCC 11.2.0
Build        : ('main', 'Oct 21 2025 20:16:04')
Arch         : ('64bit', 'ELF')
------------Pip Info-----------
Version      : 25.3
Directory    : .../anaconda3/envs/verl/lib/python3.12/site-packages/pip
vllm         : 0.11.0
sglang       : not found.
ray          : 2.53.0
torch        : 2.8.0
----------verl Info-----------
Version      : 0.7.0.dev
Directory    : .../codes/verl/verl
Commit Hash  : 246cac4ca6b0e3ce1009bc48aaa798689e0600af
----------Platform Info----------
Platform     : Linux-6.8.0-41-generic-x86_64-with-glibc2.39
system       : Linux
node         : pluslab01-h100
release      : 6.8.0-41-generic
version      : #41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024
----------Environment----------
CXX=".../anaconda3/envs/verl/bin/x86_64-conda-linux-gnu-c++"
CC=".../anaconda3/envs/verl/bin/x86_64-conda-linux-gnu-cc"
CUDA Runtime : 12.8
CUDA Compiler : Cuda compilation tools, release 12.8, V12.8.93
----------System Info----------
CPU Memory      : 2267.52 GB
GPU Count       : 8
GPU 1   Type    : NVIDIA H100 80GB HBM3
GPU 1   Memory  : 79.65 GB
GPU 2   Type    : NVIDIA H100 80GB HBM3
GPU 2   Memory  : 79.65 GB
GPU 3   Type    : NVIDIA H100 80GB HBM3
GPU 3   Memory  : 79.65 GB
GPU 4   Type    : NVIDIA H100 80GB HBM3
GPU 4   Memory  : 79.65 GB
GPU 5   Type    : NVIDIA H100 80GB HBM3
GPU 5   Memory  : 79.65 GB
GPU 6   Type    : NVIDIA H100 80GB HBM3
GPU 6   Memory  : 79.65 GB
GPU 7   Type    : NVIDIA H100 80GB HBM3
GPU 7   Memory  : 79.65 GB
GPU 8   Type    : NVIDIA H100 80GB HBM3
GPU 8   Memory  : 79.65 GB

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

When running the latest code with Qwen3-VL models, the following error occurs:
```
  File ".../verl/workers/rollout/vllm_rollout/vllm_async_server.py", lin
e 680, in __init__
    super().__init__(config, model_config, rollout_mode, workers, replica_rank, node_rank, gpus_per_node, nnodes)
  File ".../verl/workers/rollout/vllm_rollout/vllm_async_server.py", lin
e 198, in __init__
    self.config.max_model_len = self.model_config.hf_config.max_position_embeddings
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../transformers/configuration_utils.py", line 207, in __getattr
ibute__
    return super().__getattribute__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Qwen3VLConfig' object has no attribute 'max_position_embeddings'
```

The bug seems to be introduced after commit bb7fe68a1453f274a13b8847375b55b0c1400c1a

My script that triggers this error:
```
ENGINE=vllm
python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files=xxx/train.parquet \
    data.val_files=xxx/test.parquet \
    data.train_batch_size=128 \
    data.max_prompt_length=10000 \
    data.max_response_length=20000 \
    data.filter_overlong_prompts=True \
    data.truncation='error' \
    data.image_key=images \
    actor_rollout_ref.model.path=Qwen/Qwen3-VL-2B-Instruct \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.model.use_fused_kernels=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=128 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=10 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.01 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=80 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=$ENGINE \
    +actor_rollout_ref.rollout.engine_kwargs.vllm.disable_mm_preprocessor_cache=True \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
    actor_rollout_ref.rollout.enable_chunked_prefill=False \
    actor_rollout_ref.rollout.enforce_eager=False \
    actor_rollout_ref.rollout.free_cache_engine=True \
    actor_rollout_ref.rollout.n=5 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=40 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.use_kl_in_reward=False \
    trainer.critic_warmup=0 \
    trainer.logger='["console","wandb"]' \
    trainer.project_name='xxx' \
    trainer.experiment_name='xxx' \
    trainer.n_gpus_per_node=4 \
    trainer.nnodes=1 \
    trainer.save_freq=10 \
    trainer.test_freq=10 \
    trainer.total_epochs=15 \
    trainer.resume_mode=auto
```

### Expected behavior

For `Qwen3VLConfig` class, `max_model_len` should be inferred from `hf_config.text_config.max_position_embeddings` rather than `hf_config.max_position_embeddings`

**Comment by wuxibin89** [comment]
Fixed in https://github.com/volcengine/verl/pull/4810
